<FormItem top="Выберите метод">
    <NativeSelect placeholder="Не выбран">
        <option value="a">account.ban</option>
        <option value="a">account.changePassword</option>
        <option value="a">account.getActiveOffers</option>
        <option value="a">account.getAppPermissions</option>
        <option value="a">account.getBanned</option>
        <option value="a">account.getCounters</option>
        <option value="a">account.getInfo</option>
        <option value="a">account.ban</option>
        <option value="a">account.ban</option>
        <option value="a">account.ban</option>
        <option value="a">account.ban</option>
        <option value="a">account.ban</option>
        <option value="a">account.ban</option>
        <option value="a">account.ban</option>
        <option value="a">account.ban</option>